# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc7d7e5043dc8b627fa65ef8d7689f6f"
name = "deskapp"
handle = "deskapp-1"
application_url = "https://favorites-varied-mechanics-surge.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4782ae0e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://favorites-varied-mechanics-surge.trycloudflare.com/auth/callback",
  "https://favorites-varied-mechanics-surge.trycloudflare.com/auth/shopify/callback",
  "https://favorites-varied-mechanics-surge.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
